### PR TITLE
Create and Optimize ZFS pool for Photoprism

### PR DESCRIPTION
**Pull request by gyto6**
Still under redaction (I've been delayed).

### CODE REVIEW

**Review by gyto6 — COMMENTED** [review]
Disabling MariaDB compression and telling immediatly to mirror the Special vDev

**Review by gyto6 — COMMENTED** [review]
Added commentary to MariaDB parameter

**Review by gyto6 — COMMENTED** [review]
More commentary concerning MariaDB

**Comment by graciousgrey** [comment]
Thank you! Let us know whenever you think we should merge this :)

**Review by gyto6 — COMMENTED** [review]
More Commentary, beginning Photoprism Variables

**Review by gyto6 — COMMENTED** [review]
Added Photoprism variables, need to be read and corrected.

**Comment by gyto6** [comment]
> Thank you! Let us know whenever you think we should merge this :)

A real pleasure, moreover if it can let you more time to focus on others matters! I'm sorry if you're receiving to many notifications as long that I edit. Should be ready on Wednesday for merging I think. 
I shared the link on gitter in case some people might suggest some modifications.

**Review by gyto6 — COMMENTED** [review]
Edit Shape and Introduction

**Review by gyto6 — COMMENTED** [review]
Some edition with poolname, adding a warning.

**Review by gyto6 — COMMENTED** [review]
Finished the tutorial. Posting the conclusion

**Comment by gyto6** [comment]
@graciousgrey 
The commit is finished. You can review it, and if everything is alright, can be merged.

**Comment by graciousgrey** [comment]
Thank you :)

**Pull request merged**
